### ISSUE TITLE
Don't use // for comments in your installation commands

### ISSUE THREAD

**Issue by stanhoenson** [oracle-samples/oracleadapter-parse#12]
Hi,

In the second step on the 4th and 5th line you've added "comments", however this is not how comments work in the most used shells (bash, zsh, ksh, even Powershell). I followed the steps without looking all too critically (which is my bad of course) and the 4th step `rm -rf .git        // IMPORTANT ...` has wiped all my self-installed binaries. Because what happens is the following. 

It first deletes the `.git` directory of course, but the `rm` program can take multiple arguments, each argument being another file or directory. So it then also recursively goes through `//` (because it's seen as the second argument) which is the root of Unix based systems. Executing this command removes everything from your system it has the permissions for.

This is obviously very dangerous.

If you want to add comments to your scripts, you should use a `#`. So it would look like:

`rm -rf .git          # IMPORTANT ...`

Please change this in the README so other people don't experience the same problem as I did.

**Comment by ddrechse** [comment]
Hi Stan,

First, sincere apologies.  I will be rolling branch OracleParseStorageAdapter into main shortly and that will have this fix.

That new branch will be the official release with Parse 7.1.0 that has the fixes to support Database Adapter testing and dynamic configuration and will alos have a functioning pipeline for the Parse Server test suite.

A day or 2

Appreciate the feedback

**Comment by ddrechse** [comment]
Fixed with latest push of OracleParseStorageAdapter branch
